coreos:
    units:
        - name: '00-enp2s0f0.network'
          runtime: true
          content: |
              [Match]
              Name=enp2s0f0

              [Network]
              Gateway=10.0.0.254
              DNS=10.0.0.254
              Address=10.0.0.254/24
    ssh_autorhized_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrQtrkOMMhsFjru/cjmdddm3CiW69XGDff19u6hciIphBkYc4Zank1AKRgCRa/hkoF3KsagWTdPtmiYhJ3UEU8crbNSGJyEwiQ//m52xJutF5GZT8ygxrfCIlJfVhpJyczCnsNlskWAoDpUeoDJuikIF8jx9jmPiAGzUGZYVgAFk2VExjH15ErDofIT9LaVHhcC9ef9i6WmVyFQwEuWCmGaEt0ONmrmalLajtniQHWHeBoL3fLaqZ45qfy/MPJpm/q+Ki+CkBkrna2dGUSR25iMAJKYwb2ZmcYvsIwE5OokQ9bm5kTwh0cYM/glXYlPU4SBK1lwKK+uvuLlHDnTq75 andrewlee@wlan237-091.wireless.stolaf.edu"
